src/Entity/Objects.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ObjectsRepository")
 */
class Objects
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Contract", mappedBy="Object", cascade={"persist", "remove"})
     */
    private $contract;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Mods", inversedBy="objects")
     */
    private $Mods;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Jurnal", mappedBy="Object")
     */
    private $jurnals;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="objects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="text")
     */
    private $Url;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Rating;

    public function __construct()
    {
        $this->Mods = new ArrayCollection();
        $this->jurnals = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getContract(): ?Contract
    {
        return $this->contract;
    }

    public function setContract(Contract $contract): self
    {
        $this->contract = $contract;

        // set the owning side of the relation if necessary
        if ($this !== $contract->getObject()) {
            $contract->setObject($this);
        }

        return $this;
    }

    /**
     * @return Collection|Mods[]
     */
    public function getMods(): Collection
    {
        return $this->Mods;
    }

    public function addMod(Mods $mod): self
    {
        if (!$this->Mods->contains($mod)) {
            $this->Mods[] = $mod;
        }

        return $this;
    }

    public function removeMod(Mods $mod): self
    {
        if ($this->Mods->contains($mod)) {
            $this->Mods->removeElement($mod);
        }

        return $this;
    }

    /**
     * @return Collection|Jurnal[]
     */
    public function getJurnals(): Collection
    {
        return $this->jurnals;
    }

    public function addJurnal(Jurnal $jurnal): self
    {
        if (!$this->jurnals->contains($jurnal)) {
            $this->jurnals[] = $jurnal;
            $jurnal->addObject($this);
        }

        return $this;
    }

    public function removeJurnal(Jurnal $jurnal): self
    {
        if ($this->jurnals->contains($jurnal)) {
            $this->jurnals->removeElement($jurnal);
            $jurnal->removeObject($this);
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->Url;
    }

    public function setUrl(string $Url): self
    {
        $this->Url = $Url;

        return $this;
    }

    public function __toString()
    {
        return $this->Name;
    }

    public function getRating(): ?float
    {
        return $this->Rating;
    }

    public function setRating(?float $Rating): self
    {
        $this->Rating = $Rating;

        return $this;
    }

}

src/Form/ObjectsType.php
<?php

namespace App\Form;

use App\Entity\Objects;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ObjectsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Description')
            ->add('Price')
            ->add('Category')
            ->add('Url')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Objects::class,
        ]);
    }
}

src/Controller/ObjectsController.php
<?php

namespace App\Controller;

use App\Entity\Objects;
use App\Form\ObjectsType;
use App\Repository\CategoryRepository;
use App\Repository\ObjectsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/objects")
 */
class ObjectsController extends AbstractController
{
    /**
     * @Route("/", name="objects_index", methods={"GET"})
     */
    public function index(ObjectsRepository $objectsRepository, CategoryRepository $categoryRepository): Response
    {
        return $this->render('objects/index.html.twig', [
            'objects' => $objectsRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="objects_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $object = new Objects();
        $form = $this->createForm(ObjectsType::class, $object);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($object);
            $entityManager->flush();

            return $this->redirectToRoute('objects_index');
        }

        return $this->render('objects/new.html.twig', [
            'object' => $object,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="objects_show", methods={"GET"})
     */
    public function show(Objects $object): Response
    {
        return $this->render('objects/show.html.twig', [
            'object' => $object,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="objects_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Objects $object): Response
    {
        $form = $this->createForm(ObjectsType::class, $object);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('objects_index', [
                'id' => $object->getId(),
            ]);
        }

        return $this->render('objects/edit.html.twig', [
            'object' => $object,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="objects_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Objects $object): Response
    {
        if ($this->isCsrfTokenValid('delete'.$object->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($object);
            $entityManager->flush();
        }

        return $this->redirectToRoute('objects_index');
    }

//    /**
//     * @Route("/new", name="objects_new", methods={"GET","POST"})
//     */
//    public function new(Request $request): Response
//    {
//
//
//        $object = new Objects();
//        $form = $this->createForm(ObjectsType::class, $object);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $entityManager = $this->getDoctrine()->getManager();
//            $entityManager->persist($object);
//            $entityManager->flush();
//
//            return $this->redirectToRoute('objects_index');
//        }
//
//        return $this->render('objects/new.html.twig', [
//            'object' => $object,
//            'form' => $form->createView(),
//        ]);
//    }

    /**
     * @Route("/category/{category}", name="objects_category", methods={"GET"})
     */
    public function filtr(ObjectsRepository $objectsRepository, $category, CategoryRepository $categoryRepository): Response
    {
        return $this->render('objects/filtr.html.twig', [
            'category' => $objectsRepository->findBy(["Category" => $category]),
            'categories' => $categoryRepository->findAll(),
        ]);

    }
}

templates/objects/_delete_form.html.twig
<form method="post" action="{{ path('objects_delete', {'id': object.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ object.id) }}">
    <button class="btn">Delete</button>
</form>

templates/objects/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/objects/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Objects{% endblock %}

{% block body %}
    <h1>Edit Objects</h1>

    {{ include('objects/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('objects_index') }}">back to list</a>

    {{ include('objects/_delete_form.html.twig') }}
{% endblock %}

templates/objects/filtr.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objects index{% endblock %}

{% block body %}
    <h1>Товары</h1>
    {% if category == null %}
        <h1>В категории нет товаров ='(</h1>
    {% endif %}
        <div class="container content">
            <div class="row">
                <div class="col-12 products">
                    <div class="row">
        {% for object in category %}
                            <div class="col-sm-4">
                                <div class="product">
                                    <div class="border" id="catalog">
                                        <div class="wrap">
                                            <div class="product-wrap">
                                                <img src="{{ object.url }}" alt="">
                                            </div>
                                            <div class="loop-action">
                                                <a href="" class="loop-add-to-cart vKorzinu" data-toggle="modal" data-target="#exampleModal" data-objectId="{{ object.id }}">В корзину</a>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="product-title">
                                        <a href="{{ path('objects_show', {'id': object.id}) }}">{{ object.Name }}</a>
                                    </p>
                                    <p class="product-desc">{{ object.Description }}</p>
                                    <p class="product-price">Цена: €{{ object.Price }}</p>
                                </div>
                            </div>
        {% endfor %}


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Сделайте заказ</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">

                                        {{ render(controller('App\\Controller\\ContractController::new')) }}

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

templates/objects/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objects index{% endblock %}

{% block body %}
    <h1>Objects index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for object in objects %}
            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.Name }}</td>
                <td>{{ object.Price }}</td>
                <td>
                    <a href="{{ path('objects_show', {'id': object.id}) }}">show</a>
                    <a href="{{ path('objects_edit', {'id': object.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('objects_new') }}">Create new</a>
{% endblock %}

templates/objects/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Objects{% endblock %}

{% block body %}
    <h1>Create new Objects</h1>

    {{ include('objects/_form.html.twig') }}

    <a href="{{ path('objects_index') }}">back to list</a>
{% endblock %}

templates/objects/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objects{% endblock %}

{% block body %}
    {#    <h1>Objects</h1>#}

    {#    <table class="table">#}
    {#        <tbody>#}
    {#            <tr>#}
    {#                <th>Id</th>#}
    {#                <td>{{ object.id }}</td>#}
    {#            </tr>#}
    {#            <tr>#}
    {#                <th>Name</th>#}
    {#                <td>{{ object.Name }}</td>#}
    {#            </tr>#}
    {#            <tr>#}
    {#                <th>Price</th>#}
    {#                <td>{{ object.Price }}</td>#}
    {#            </tr>#}
    {#        </tbody>#}
    {#    </table>#}

    {#    <a href="{{ path('objects_index') }}">back to list</a>#}

    {#    <a href="{{ path('objects_edit', {'id': object.id}) }}">edit</a>#}

    {#    {{ include('objects/_delete_form.html.twig') }}#}
    <div class="form-inline">
        <div class="product-show">
            <img src="{{ object.url }}" alt="">
        </div>
            <div class="product-text-show">
                <h6>{{ object.description }}</h6>
            </div>
    </div>
{% endblock %}